version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: dockerfile-node-img
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

