# Use an official Node runtime as the base image
FROM node:22

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm cache clean --force
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Set environment variable for Node.js
ENV NODE_OPTIONS=--openssl-legacy-provider

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app when the container launches
CMD ["npm", "start"]

# Inicia el contenedor con /bin/sh por defecto
# CMD ["/bin/sh"]
